### ISSUE TITLE
Add Contribution.md File

### ISSUE THREAD

**Issue by whythoSanskar** [whythoSanskar/TwitterBot#6]
- Add the contribution rules in the contribution.md file 
- Also add the hacktoberfest contribution guidelines to Contribution.md

**Comment by atiqueakhtar** [comment]
Will raise a PR to update the contribution.md as per the requirement.

**Comment by yashgosa** [comment]
hey @whythoSanskar I have created a pr if you like  it please accept it as contribution for hacktoberfest. If there's any  changes required feel free.

**Comment by atiqueakhtar** [comment]
Hi @whythoSanskar my PR with better and crisp CONTRIBUTION.md is ready with hacktoberfest rules also included. I will raise it now.

**Comment by whythoSanskar** [comment]
Ok relax, @sofezticated-gentleman and @atiqueakhtar. Kindly make a PR and I'll review it.

**Comment by whythoSanskar** [comment]
Closed as completed in #9
