### ISSUE TITLE
Add CodeofConduct.md file

### ISSUE THREAD

**Issue by whythoSanskar** [whythoSanskar/TwitterBot#7]
- Add the code of conduct.MD file, add the rules relevant to the code of conduct
- Add hacktoberfest Contributors guidelines.

**Comment by yash206** [comment]
please assign this role to me

**Comment by yash206** [comment]
@whythoSanskar allow me to add

**Comment by whythoSanskar** [comment]
Sure @yash206, go ahead and work on it.

**Comment by whythoSanskar** [comment]
Closed this as completed in #11
